name: CI

on:
  push:
    branches:
      - dev
      - security-test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'
          cache: maven
      - name: Test with Maven
        run: mvn test
      - name: Build with Maven
        run: mvn -B package --file pom.xml